version: "3"

# dev environment
# docker-compose up

services:
  web:
    container_name: dockerizing-web-dev
    build:
      context: ./web
      dockerfile: dev.dockerfile
    volumes:
      - ./web:/home/node/app
    ports:
      - 3000:3000
    command: ["yarn", "start"]
  api:
    container_name: dockerizing-api-dev
    image: node:6-alpine
    volumes:
      - ./api:/home/node/app
    working_dir: /home/node/app
    ports:
      - 3001:80
      - 5858:5858
    command: ["yarn", "start"]