version: "3"

# dev environment
# this file extends docker-compose.yml
# docker-compose up

services:
  web:
    container_name: dockerizing-web-dev
    build:
      context: "./web"
      dockerfile: "dev.dockerfile"
    volumes:
      - ./web:/home/node/app
    ports:
      - 3000:3000
    command: ["yarn", "start"]