
version: "3"

# prod environment
# this file extends docker-compose.yml
# docker-compose -f docker-compose.prod.yml up -d

services:
  web:
    container_name: dockerizing-web
    build:
      context: "./web"
      dockerfile: "prod.dockerfile"
    ports:
      - "8080:80"