version: "3"

# prod environment
# docker-compose -f docker-compose.prod.yml up --build

services:
  web:
    container_name: dockerizing-web
    build:
      context: "./web"
      dockerfile: "prod.dockerfile"
    ports:
      - "8080:80"
  api:
    container_name: dockerizing-api
    build:
      context: "./api"
      dockerfile: "prod.dockerfile"